#spring jsckson
spring: 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
logging:
  config: classpath:logback.xml
  
#socket config
socket:
  port: 9090
  heartBeat: 600
  
#redis config
redis:
  ip: 127.0.0.1
  port: 6379